name: PullRequest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  buildTest:
    name: Build with JDK ${{ matrix.java_version }}
    runs-on: macOS-latest
    strategy:
      matrix:
        java_version: [ 11.0.3 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.1
      - name: Build project
        run: ./gradlew assembleDebug
